// const placeholder = {
//   id: 10,
//   slug: "",
//   title: "",
//   summary: "",
//   content: "",
//   author: "",
//   authorImage: "",
//   authorTitle: "",
//   date: "",
//   lastModified: "",
//   category: "",
//   imageUrl: "",
//   keywords: [""],
//   wordCount: 0,
//   isAccessibleForFree: true,
//   mainEntity: "",
// };

export const NEWSDATA = [
  {
    id: 10,
    slug: "deepseek-v3-model-and-us-nebula",
    title:
      "DeepSeek’s Surprise V3 Drop Hints at Bigger Things — and a US Showdown",
    summary:
      "DeepSeek quietly dropped a powerful V3 model, and all eyes are now on what comes next: R2 and a potential clash with America’s top contenders.",
    content:
      "China’s DeepSeek just shadow-dropped a new version of V3 — the base model that came out before R1 — that weighs in at just 641 GB, meaning it could theoretically run on a high-end Mac.\n\nIt seems to be especially good at math and coding, and AI researcher Xeophon even called it the “best non-reasoning model, dethroning [Anthropic’s] Sonnet 3.5.” Plus, it was released with an MIT license, meaning anyone can tweak and adapt it with very few restrictions.\n\nBut this might just be the appetizer before the main course: V3 served as the base for R1, the reasoning-focused model that shocked the industry earlier this year. If that trend continues, DeepSeek will likely use this new model to train R2. And we probably don’t have too long to wait, with reports suggesting it could be here before May.\n\nBut the US might already have its answer: A mysterious new model called “Nebula” recently jumped to the top of the LMArena leaderboard — and rumor has it that it’s a soon-to-be-released model called Gemini 2.0 Pro Thinking. Google’s own research scientists are winking at the possibility. It looks like we’re headed toward a major showdown between DeepSeek and its well-funded US counterparts.",
    author: "Legatus",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "AI News Editor",
    date: "2025-04-15",
    lastModified: "2025-04-15",
    category: "AI News",
    imageUrl: require("assets/images/deepseek_news.png"),
    keywords: [
      "DeepSeek",
      "V3",
      "R1",
      "Gemini 2.0 Pro",
      "Nebula",
      "AI models",
      "China AI",
    ],
    wordCount: 270,
    isAccessibleForFree: true,
    mainEntity: "DeepSeek",
  },
  {
    id: 9,
    slug: "google-gemini-major-release",
    title: "Google Fires Back: Gemini Drops Major Features in AI Showdown",
    summary:
      "From Flash models to media generation tools, Google’s latest Gemini drop is an aggressive move to dominate the AI race.",
    content:
      "The gloves are officially off. The Gemini maker pulled out all the stops, announcing a series of new releases focused on thinking models, agent ecosystems, and more. Here’s the most important stuff you need to know:\n\nGemini 2.5 Flash: Built for efficiency, 2.5 Flash offers developers speed and efficiency while incorporating thinking capabilities.\n\nFirebase Studio: In a bid to take on Cursor, Bolt, and others, the search giant announced Firebase Studio, an end-to-end platform that lets users build and deploy apps with a few simple prompts.\n\nVeo 2 in API: Developers now have access to the company’s premier video generation model via the Gemini API. Users, with billing enabled at Tier 1 and above, can access the model in the API, with support for text-to-video and image-to-video.\n\nLive API: The company’s Live API has officially launched for production use, now featuring support for 30 additional languages, two new voices, enhanced voice detection options, and an intuitive new UI.\n\nIronwood: The company’s 7th gen TPU, which purportedly pumps out more than 42 exaflops of computing power per pod of 9,216 chips, packs 192GB memory capacity (6x its predecessor), and faster data access.\n\nAgent2Agent: A new open protocol geared towards helping AI agents collaborate securely across ecosystems.\n\nMedia gen tools for Vertex AI: Major updates include Lyria for text-to-music creation, enhanced video editing controls for Veo 2, and Chirp 3's new 10-second custom voice feature.",
    author: "Legatus",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "PK",
    date: "2025-04-15",
    lastModified: "2025-04-15",
    category: "AI News",
    imageUrl: require("assets/images/gemini_news.png"),
    keywords: [
      "Gemini",
      "Google AI",
      "Firebase Studio",
      "Gemini Flash",
      "Veo 2",
      "Agent2Agent",
      "Vertex AI",
    ],
    wordCount: 270,
    isAccessibleForFree: true,
    mainEntity: "Gemini",
  },
  {
    id: 8,
    slug: "chatgpt-viral-ghibli-action-figure-trend",
    title:
      "From Ghibli Dreams to Action Figure Fame: How ChatGPT is Turning “Toys” Into Global Trends",
    summary:
      "ChatGPT's Ghibli image feature sparked a global trend, especially in India, helping the app top global downloads. Now, a new wave of action figure-style images hints that the next big thing in tech might once again look like a toy.",
    content:
      "Chris Dixon once said, “The next big thing will start out looking like a toy.” That insight from 2010 continues to hold true — especially in the case of ChatGPT’s latest viral wave: Studio Ghibli-style image generation.\n\nIt began innocently enough. People around the world uploaded selfies and watched as ChatGPT transformed them into enchanting, Ghibli-inspired artwork.But behind the whimsical fun was a serious surge in user growth. While social feeds filled with dreamy anime portraits, ChatGPT quietly shattered records. On March 31, OpenAI CEO Sam Altman wrote, “The ChatGPT launch 26 months ago was one of the craziest viral moments I'd ever seen, and we added one million users in five days. We added one million users in the last hour.”\n\nOne of the biggest revelations from this trend? India. The Ghibli-style craze resonated deeply across the subcontinent, catalyzing an explosion in new users.\n\nOpenAI COO Brad Lightcap called India their fastest-growing market for ChatGPT, and Altman even joined the party, posting a Ghibli image of himself playing cricket — an unmistakable nod to Indian users. The result: ChatGPT became the most downloaded app globally in March.\n\nNow, another viral wave is forming. Users are beginning to create action figure-style images of themselves and celebrities, further pushing the boundaries of how we interact with AI and self-expression. Once again, something that looks like a toy is becoming the centerpiece of a tech movement.\n\nThe next big thing? It just might be made of plastic.",
    author: "Legatus",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "PK",
    date: "2025-04-15",
    lastModified: "2025-04-15",
    category: "Trends",
    imageUrl: require("assets/images/Action_Figure_1.png"),
    keywords: [
      "ChatGPT",
      "Ghibli trend",
      "AI images",
      "India tech",
      "Sam Altman",
      "OpenAI",
      "action figure",
      "viral trends",
    ],
    wordCount: 497,
    isAccessibleForFree: true,
    mainEntity: "ChatGPT",
  },
  {
    id: 2,
    slug: "company-announces-new-enterprise-plan-advanced-security",
    title:
      "Company Announces New Enterprise Plan with Advanced Security Features",
    summary:
      "Our latest enterprise plan includes enhanced encryption, multi-factor authentication, and comprehensive audit logs for businesses with stringent security requirements.",
    content:
      "Today, we're excited to announce our new Enterprise+ plan, designed specifically for organizations that require the highest level of security and compliance features. The plan includes end-to-end encryption for all data, advanced multi-factor authentication options, detailed access control systems, and comprehensive audit logs that meet the requirements of GDPR, HIPAA, and other regulatory frameworks.",
    author: "Michael Rodriguez",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "Product Manager",
    date: "2025-04-08T14:15:00",
    lastModified: "2025-04-09T11:30:00",
    category: "Product",
    imageUrl: require("assets/images/ai_rome_2.png"),
    keywords: [
      "enterprise plan",
      "security",
      "encryption",
      "multi-factor authentication",
      "audit logs",
      "compliance",
    ],
    wordCount: 185,
    isAccessibleForFree: true,
    mainEntity: "Enterprise Software",
  },
  {
    id: 3,
    slug: "annual-developer-conference-september-2025",
    title: "Annual Developer Conference Scheduled for September 2025",
    summary:
      "Mark your calendars for our biggest event of the year. Early bird registration is now open with special workshop sessions available for premium ticket holders.",
    content:
      "We're thrilled to announce our annual Developer Conference will take place September 15-17, 2025 at the San Francisco Convention Center. This year's theme is 'Building the Intelligent Future,' with keynote presentations focusing on AI integration, cloud architecture, and secure development practices. Early bird registration is now open, with a 25% discount available until June 1st.",
    author: "Jessica Lee",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "Events Director",
    date: "2025-04-05T11:00:00",
    lastModified: "2025-04-06T08:45:00",
    category: "Events",
    imageUrl: require("assets/images/futuristic_virtual_technology_summit.png"),
    keywords: [
      "developer conference",
      "technology",
      "AI",
      "cloud architecture",
      "development practices",
      "San Francisco",
    ],
    wordCount: 168,
    isAccessibleForFree: true,
    mainEntity: "Developer Conferences",
  },
  {
    id: 4,
    slug: "strategic-partnership-leading-cloud-provider",
    title: "Strategic Partnership Announced with Leading Cloud Provider",
    summary:
      "Our new collaboration will enable seamless integration between platforms and provide customers with enhanced performance and reliability.",
    content:
      "We're excited to announce a strategic partnership with CloudTech Solutions, one of the world's leading cloud infrastructure providers. This collaboration will enable our customers to benefit from enhanced performance, improved reliability, and seamless integration between our platforms. The partnership includes joint development of new features, optimized deployment options, and special pricing packages for users of both services.",
    author: "Robert Johnson",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "Strategic Partnerships Lead",
    date: "2025-04-03T16:45:00",
    lastModified: "2025-04-04T14:00:00",
    category: "Business",
    imageUrl: require("assets/images/futuristic_solar_panels.png"),
    keywords: [
      "strategic partnership",
      "cloud provider",
      "integration",
      "performance",
      "reliability",
      "CloudTech Solutions",
    ],
    wordCount: 155,
    isAccessibleForFree: true,
    mainEntity: "Cloud Computing",
  },
  {
    id: 5,
    slug: "new-mobile-app-version-redesigned-interface-performance",
    title:
      "New Mobile App Version Features Redesigned Interface and Performance Improvements",
    summary:
      "Version 3.0 of our mobile application introduces a cleaner, more intuitive interface along with significant performance optimizations for faster load times.",
    content:
      "Today we're rolling out version 3.0 of our mobile application for both iOS and Android platforms. This major update features a completely redesigned user interface based on extensive user feedback and usability testing. The new design offers a more intuitive navigation system, customizable dashboard, and improved accessibility features. Additionally, we've optimized performance across the board, resulting in 40% faster load times and reduced battery consumption.",
    author: "Amanda Chen",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "Mobile Development Lead",
    date: "2025-04-01T10:20:00",
    lastModified: "2025-04-02T09:15:00",
    category: "Product",
    imageUrl: require("assets/images/bg_remover_web_interface.png"),
    keywords: [
      "mobile app",
      "update",
      "redesign",
      "user interface",
      "performance",
      "iOS",
      "Android",
    ],
    wordCount: 178,
    isAccessibleForFree: true,
    mainEntity: "Mobile Applications",
  },
  {
    id: 6,
    slug: "company-opens-new-office-singapore-apac-expansion",
    title:
      "Company Opens New Office in Singapore to Support Asia-Pacific Expansion",
    summary:
      "Our new regional headquarters will better serve our growing customer base in the APAC region and supports our global expansion strategy.",
    content:
      "We're proud to announce the opening of our new Asia-Pacific headquarters in Singapore. This expansion represents a significant milestone in our global growth strategy and will allow us to better serve our rapidly growing customer base in the region. The new office will house sales, customer support, and technical teams dedicated to providing localized service and support for our APAC clients. We expect to hire more than 200 employees for the Singapore office by the end of 2025.",
    author: "David Wong",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "VP of International Operations",
    date: "2025-03-28T09:00:00",
    lastModified: "2025-03-29T12:30:00",
    category: "Company",
    imageUrl: require("assets/images/lesson_tree.png"),
    keywords: [
      "company expansion",
      "new office",
      "Singapore",
      "Asia-Pacific",
      "APAC",
      "global strategy",
    ],
    wordCount: 165,
    isAccessibleForFree: true,
    mainEntity: "Business Expansion",
  },
  {
    id: 1,
    slug: "new-ai-algorithm-improves-accuracy-in-image-recognition",
    title: "New AI Algorithm Improves Accuracy in Image Recognition by 30%",
    summary:
      "Our team has developed a groundbreaking algorithm that significantly improves the accuracy of image recognition systems, particularly in low-light environments.",
    content:
      "Our research team has achieved a major breakthrough in AI image recognition technology. The newly developed algorithm demonstrates a 30% improvement in accuracy compared to current industry standards, especially in challenging low-light conditions. This advancement will enable more reliable facial recognition systems, autonomous vehicles with improved safety features, and enhanced medical imaging analysis.",
    author: "Dr. Sarah Chen",
    authorImage: require("assets/images/legatus_person.png"),
    authorTitle: "Lead AI Researcher",
    date: "2025-04-10T09:30:00",
    lastModified: "2025-04-12T10:00:00",
    category: "Technology",
    imageUrl: require("assets/images/image_observer_web_dashboard.png"),
    keywords: [
      "AI",
      "image recognition",
      "algorithm",
      "machine learning",
      "low-light",
      "accuracy",
    ],
    wordCount: 210,
    isAccessibleForFree: true,
    mainEntity: "Artificial Intelligence",
  },
];
